### ISSUE TITLE
Status of this repo

### ISSUE THREAD

**Issue by MPortGroup** [Demon000/device_xiaomi_sm8350-common#1]
Hi! I think your repo is amazing! Thank you very much for your work.

I am currently trying to create ROMs for Xiaomi Mix 4 (odin) which is based on sm8350. I had several attempts but none of them boots. Just out of curiosity, are you able to use this repo's device tree to create ROM and boot successfully? I'm trying to figure out which part of my port is not working. Thanks again for this awesome repo!

**Comment by yogevm15** [comment]
Demon000 built lineageos for venus(Mi 11) using his trees and it's booting.
You can join this telegram group for more details about his build.
https://t.me/mi11chat

**Comment by Demon000** [comment]
It boots. FOD isn't implemented yet.
